dataset:
  annotation:
    conf_type: ANNOT_FILE
    name: activity-1s
    version: ''
    path:
      dir: ${path.openpack.rootdir}/${user.name}/annotation/activity-1s/
      fname: ${session}.csv
    file_format: null
    classes: ???
    activity_sets:
      openpack-operations:
        classes:
        - id: 100
          name: Picking
          is_ignore: false
        - id: 200
          name: Relocate Item Label
          is_ignore: false
        - id: 300
          name: Assemble Box
          is_ignore: false
        - id: 400
          name: Insert Items
          is_ignore: false
        - id: 500
          name: Close Box
          is_ignore: false
        - id: 600
          name: Attach Box Label
          is_ignore: false
        - id: 700
          name: Scan Label
          is_ignore: false
        - id: 800
          name: Attach Shipping Label
          is_ignore: false
        - id: 900
          name: Put on Back Table
          is_ignore: false
        - id: 1000
          name: Fill out Order
          is_ignore: false
        - id: 8100
          name: 'Null'
          is_ignore: true
      openpack-actions:
        classes:
        - id: 101
          name: Pick Up Sheet
          is_ignore: false
        - id: 103
          name: Pick Up Item from Box
          is_ignore: false
        - id: 107
          name: Pick Up Box Sheet
          is_ignore: false
        - id: 108
          name: Walk to Work Bench
          is_ignore: false
        - id: 109
          name: Put Packed Box
          is_ignore: false
        - id: 201
          name: Remove Item Label
          is_ignore: false
        - id: 202
          name: Attach to Order Sheet
          is_ignore: false
        - id: 203
          name: Hold Pen
          is_ignore: false
        - id: 204
          name: Write Check Mark
          is_ignore: false
        - id: 205
          name: Put Item Small Bag
          is_ignore: false
        - id: 301
          name: Pick Cardboard
          is_ignore: false
        - id: 302
          name: Bend Flap
          is_ignore: false
        - id: 303
          name: Attach Tape
          is_ignore: false
        - id: 304
          name: Turn Over Box
          is_ignore: false
        - id: 305
          name: Pick Up Assembled Box
          is_ignore: false
        - id: 401
          name: Insert Item into Box
          is_ignore: false
        - id: 402
          name: Air Cushion
          is_ignore: false
        - id: 403
          name: Separate Air Cushion
          is_ignore: false
        - id: 404
          name: Put Item Small Bag
          is_ignore: false
        - id: 501
          name: Bend Flap
          is_ignore: false
        - id: 502
          name: Attach Tape
          is_ignore: false
        - id: 601
          name: Attach Box Label
          is_ignore: false
        - id: 701
          name: Pick Up HT
          is_ignore: false
        - id: 702
          name: Scan Order Sheet
          is_ignore: false
        - id: 703
          name: Scan Box
          is_ignore: false
        - id: 704
          name: Scan Item
          is_ignore: false
        - id: 705
          name: Hold Scanner
          is_ignore: false
        - id: 706
          name: Scan Order Sheet
          is_ignore: false
        - id: 707
          name: Scan Printer
          is_ignore: false
        - id: 801
          name: Pick Up Shipping Label
          is_ignore: false
        - id: 802
          name: Attach Shipping Label
          is_ignore: false
        - id: 901
          name: Pick Up Packed Box
          is_ignore: false
        - id: 902
          name: Put Packed Box
          is_ignore: false
        - id: 1001
          name: Pick Up Pen
          is_ignore: false
        - id: 1002
          name: Write Sign
          is_ignore: false
        - id: 1003
          name: Push Order Sheet into Tray
          is_ignore: false
        - id: 8101
          name: Others
          is_ignore: true
        - id: 8102
          name: System Error
          is_ignore: true
        - id: 8103
          name: Ignore
          is_ignore: true
        - id: 8104
          name: Unknown
          is_ignore: true
        - id: 8201
          name: System Error
          is_ignore: true
  stream:
    name: all_imu_keypoint
    super_stream: None
    clip_base_ts: keypoint
    path_imu:
      dir: ${path.openpack.rootdir}/${user.name}/atr/${device}
      fname: ${session}.csv
    frame_rate_imu: 30
    devices:
    - atr01
    - atr02
    - atr03
    - atr04
    acc: true
    gyro: false
    quat: false
    imu_dim: 12
    min_value_imu_acc: -4
    max_value_imu_acc: 4
    min_value_imu_gyro: -2000
    max_value_imu_gyro: 2000
    path_keypoint:
      dir: ${path.openpack.rootdir}/${user.name}/kinect/${..category}/${..model}/single
      fname: ${session}.json
    frame_rate_keypoint: 15
    category: 2d-kpt
    model: mmpose-hrnet-w48-posetrack18-384x288-posewarper-stage2
    nodes:
      0: nose
      1: left_eye
      2: right_eye
      3: left_ear
      4: right_ear
      5: left_shoulder
      6: right_shoulder
      7: left_elbow
      8: right_elbow
      9: left_wrist
      10: right_wrist
      11: left_hip
      12: right_hip
      13: left_knee
      14: right_knee
      15: left_ankle
      16: right_ankle
    keypoint_dim: 34
    min_value_keypoint: 0
    max_value_keypoint: 1280
    path_e4acc:
      dir: ${path.openpack.rootdir}/${user.name}/e4/${device}/acc
      fname: ${session}.csv
    frame_rate_e4acc: 32
    devices_e4acc:
    - e401
    - e402
    e4acc_dim: 6
    min_value_e4acc: -0.204
    max_value_e4acc: 0.204
    bbox_dim: 4
    min_value_bbox: 0
    max_value_bbox: 1280
    path_e4bvp:
      dir: ${path.openpack.rootdir}/${user.name}/e4/${device}/bvp
      fname: ${session}.csv
    frame_rate_e4bvp: 64
    devices_e4bvp:
    - e401
    - e402
    path_e4eda:
      dir: ${path.openpack.rootdir}/${user.name}/e4/${device}/eda
      fname: ${session}.csv
    frame_rate_e4eda: 4
    devices_e4eda:
    - e401
    - e402
    path_e4temp:
      dir: ${path.openpack.rootdir}/${user.name}/e4/${device}/temp
      fname: ${session}.csv
    frame_rate_e4temp: 4
    devices_e4temp:
    - e401
    - e402
    path_ht:
      dir: ${path.openpack.rootdir}/${user.name}/system/ht
      fname: ${session}.csv
    frame_rate_ht: -1
    path_order:
      dir: ${path.openpack.rootdir}/${user.name}/system/order-sheet/
      fname: ${session}.csv
    frame_rate_order: -1
    path_printer:
      dir: ${path.openpack.rootdir}/${user.name}/system/printer
      fname: ${session}.csv
    frame_rate_printer: -1
    path_kinect_depth:
      dir: ${path.openpack.rootdir}/${user.name}/kinect/depth/frames_resize224
      fname: ${session}.csv
    frame_rate_kinect_depth: 15
    kinect_depth_dim: 4096
    min_value_kinect_depth: 0
    max_value_kinect_depth: 13000
    mean_image_kinect_depth:
      dir: ${path.openpack.rootdir}/mean_image/kinect_depth
      fname: split${dataset.k_fold}.png
    path_rs02_depth:
      dir: ${path.openpack.rootdir}/${user.name}/rs02/depth/frames_resize224
      fname: ${session}.csv
    frame_rate_rs02_depth: 7
    rs02_depth_dim: 12288
    mean_image_rs02_depth:
      dir: ${path.openpack.rootdir}/mean_image/rs02_depth
      fname: split${dataset.k_fold}.png
    path_kinect_feature:
      dir: /workspace/kinect_feature/${cnn_feature.issue}/split${dataset.k_fold}/${user.name}/
      fname: ${session}.csv
    path_kinect_feature_all:
      dir: /workspace/kinect_feature/${cnn_feature.issue}/split${dataset.k_fold}/${user.name}/${session}
      unixtime_fname: all_unixtime.npy
      feat_fname: all_feat.npy
    frame_rate_kinect_feature: 15
    kinect_feature_dim: 2048
    path_mean_image_kinect_feature:
      dir: /workspace/kinect_feature/${cnn_feature.issue}/split${dataset.k_fold}/
      fname: mean_feat.npy
  split:
    name: openpack-challenge-2022
    train:
    - - U0101
      - S0100
    - - U0101
      - S0200
    - - U0101
      - S0400
    - - U0101
      - S0500
    - - U0102
      - S0100
    - - U0102
      - S0200
    - - U0102
      - S0400
    - - U0102
      - S0500
    - - U0103
      - S0100
    - - U0103
      - S0200
    - - U0103
      - S0400
    - - U0103
      - S0500
    - - U0105
      - S0100
    - - U0105
      - S0200
    - - U0105
      - S0400
    - - U0105
      - S0500
    - - U0106
      - S0100
    - - U0106
      - S0200
    - - U0106
      - S0400
    - - U0106
      - S0500
    - - U0107
      - S0100
    - - U0107
      - S0200
    - - U0107
      - S0400
    - - U0107
      - S0500
    - - U0109
      - S0100
    - - U0109
      - S0200
    - - U0109
      - S0400
    - - U0109
      - S0500
    - - U0111
      - S0100
    - - U0111
      - S0200
    - - U0111
      - S0400
    - - U0111
      - S0500
    - - U0202
      - S0100
    - - U0202
      - S0200
    - - U0202
      - S0400
    - - U0202
      - S0500
    - - U0205
      - S0100
    - - U0205
      - S0200
    - - U0205
      - S0400
    - - U0205
      - S0500
    - - U0210
      - S0100
    - - U0210
      - S0200
    - - U0210
      - S0400
    - - U0210
      - S0500
    val:
    - - U0101
      - S0300
    - - U0103
      - S0300
    - - U0105
      - S0300
    - - U0107
      - S0300
    - - U0109
      - S0300
    - - U0111
      - S0300
    - - U0205
      - S0300
    test:
    - - U0102
      - S0300
    - - U0106
      - S0300
    - - U0202
      - S0300
    - - U0210
      - S0300
    submission:
    - - U0104
      - S0100
    - - U0104
      - S0300
    - - U0108
      - S0100
    - - U0108
      - S0200
    - - U0108
      - S0300
    - - U0108
      - S0500
    - - U0110
      - S0100
    - - U0110
      - S0200
    - - U0110
      - S0300
    - - U0110
      - S0400
    - - U0110
      - S0500
    - - U0203
      - S0100
    - - U0203
      - S0200
    - - U0203
      - S0300
    - - U0203
      - S0400
    - - U0203
      - S0500
    - - U0204
      - S0200
    - - U0204
      - S0300
    - - U0204
      - S0400
    - - U0207
      - S0300
    - - U0207
      - S0400
    - - U0207
      - S0500
  classes:
    classes:
    - id: 100
      name: Picking
      is_ignore: false
    - id: 200
      name: Relocate Item Label
      is_ignore: false
    - id: 300
      name: Assemble Box
      is_ignore: false
    - id: 400
      name: Insert Items
      is_ignore: false
    - id: 500
      name: Close Box
      is_ignore: false
    - id: 600
      name: Attach Box Label
      is_ignore: false
    - id: 700
      name: Scan Label
      is_ignore: false
    - id: 800
      name: Attach Shipping Label
      is_ignore: false
    - id: 900
      name: Put on Back Table
      is_ignore: false
    - id: 1000
      name: Fill out Order
      is_ignore: false
    - id: 8100
      name: 'Null'
      is_ignore: true
  name: all
datarootdir: "/workspace/data/openpack/"
issue: ${model.name}-seed${seed}-d${model.depth}-h${model.heads}-np${model.num_patches}-pe${model.use_pe}-timestep${model.time_step_width}-bs${train.batch_size}-lr${train.optimizer.lr}-labelsm${train.label_smoothing}-mixup${train.dataaug.mixup_alpha}_${train.dataaug.mixup_p}-shuffle${train.dataaug.shuffle_alpha}_${train.dataaug.shuffle_p}-w_kappa_loss${loss.w_kappa_loss}-imu${model.imu_dim}_keypoint${model.keypoint_dim}-ht${model.ht_dim}_printer${model.printer_dim}
wandb:
  project: openpack_newSplits
debug: false
mode: test
seed: 69
model:
  name: conv_transformer_avec_plusLSTM
  dim: -1
  depth: 6
  heads: 20
  dim_head: 64
  mlp_dim: 2048
  emb_dropout: 0.2
  dropout: 0.2
  use_pe: false
  embedding_method: linear
  imu_dim: 300
  keypoint_dim: 300
  e4acc_dim: 0
  bbox_dim: 200
  ht_dim: 30
  printer_dim: 30
  kinect_depth_dim: 0
  rs02_depth_dim: 0
  resnet1d: false
  st_gcn: false
  resnet: true
  resnet_cifar: false
  mbconv: false
  num_patches: 50
  time_step_width: 1000
  use_substitute_image: false
  use_substitute_emb: false
  use_only_one_image: false
  use_pretrained_resnet: true
  add_defect_info: false
  use_mean_image: true
  use_cnn_feature: false
  image_size: 64
dataload:
  pre_image: false
  all_image_path:
    dir: ${path.openpack.rootdir}/${user.name}/kinect/depth/frames_resize224/${session}
    fname: all_images_size${model.image_size}.npy
resnet1d:
  n_layers: 2
  type: vit
st_gcn:
  Ks: 3
  Kt: 3
  type: ori
resnet:
  n_layers: 2
  type: vit
resnet_cifar:
  n_blocks: 1
mbconv:
  n_layers: 2
  type: gn
loss:
  w_kappa_loss: 0
  w_kappa_loss_weightage: linear
  ib_loss: 0
  focal_loss_gamma: 0
train:
  num_workers: -1
  batch_size: 32
  epochs: 200
  grad_clip_norm: 1.0
  label_smoothing: 0
  ignore_index: true
  inner_loss: 0.5
  optimizer:
    decrease_lr: false
    type: Adam
    lr: 0.0001
    weight_decay: 0.0001
    lr_scheduler: ori_warmup
    warmup_step: 50
    cosine_step: 40
    multistep_gamma: 0.5
    multistep_milestones:
    - 50
    - 100
    - 150
  dataaug:
    mixup_alpha: 0.8
    mixup_p: 0.5
    shuffle_alpha: 0.2
    shuffle_p: 0
    cutout_p: 0
  debug:
    batch_size: 64
    epochs: 5
twostep_pretrain:
  use: false
  pretrain_epoch: 50
pre_data_aug:
  use: false
  rotate: 2
  shift: 2
  flip_p: 0
cnn_feature:
  issue: R3D50-kinect-width${model.time_step_width}-pretrainTrue
path:
  openpack:
    version: v0.3.1
    rootdir: ${datarootdir}/${.version}
  logdir:
    rootdir: /workspace/logs/${dataset.name}/${model.name}/${issue}
    model: ${path.logdir.rootdir}/model.pth
    predict: ${path.logdir.rootdir}/pred/{user}-{session}
    summary:
      test: ${path.logdir.rootdir}/summary.csv
      submission: ${path.logdir.rootdir}/summary_submission.csv
